file(READ "${SRC}/src/http_types.c" CONTENT)
string(REPLACE "static enum c_abstract_http_error c_abstract_http_strdup" "enum c_abstract_http_error c_abstract_http_strdup" CONTENT "${CONTENT}")
file(WRITE "${SRC}/src/http_types.c" "${CONTENT}")
file(READ "${SRC}/CMakeLists.txt" CONTENT)
if(NOT CONTENT MATCHES "add_compile_options\\(\\\$<\\$<C_COMPILER_ID:MSVC>:/w>")
    string(REPLACE "-Werror" "" CONTENT "${CONTENT}")
    string(REPLACE "/WX" "" CONTENT "${CONTENT}")
    string(REGEX REPLACE "/W[1-4]" "" CONTENT "${CONTENT}")
    string(REPLACE "-Wall" "" CONTENT "${CONTENT}")
    string(REPLACE "-Wextra" "" CONTENT "${CONTENT}")
    string(REPLACE "-Wconversion" "" CONTENT "${CONTENT}")
    string(REPLACE "-Wsign-conversion" "" CONTENT "${CONTENT}")
    string(REPLACE "-pedantic" "" CONTENT "${CONTENT}")
    string(APPEND CONTENT "\nadd_compile_options($<$<C_COMPILER_ID:MSVC>:/w> $<$<NOT:$<C_COMPILER_ID:MSVC>>:-w>)\n")
    file(WRITE "${SRC}/CMakeLists.txt" "${CONTENT}")
endif()
