file(READ "${SRC}/CMakeLists.txt" CONTENT)
string(REPLACE ";-WX;" ";" CONTENT "${CONTENT}")
string(REPLACE "/WX" "" CONTENT "${CONTENT}")
file(WRITE "${SRC}/CMakeLists.txt" "${CONTENT}")
string(REGEX REPLACE "-Werror(;|=|[-a-zA-Z0-9_]+)?" "" CONTENT "${CONTENT}")
file(WRITE "${SRC}/CMakeLists.txt" "${CONTENT}")
string(REPLACE "/NODEFAULTLIB:LIBCMTD" "" CONTENT "${CONTENT}")
file(WRITE "${SRC}/CMakeLists.txt" "${CONTENT}")
