file(READ "${SRC}/include/c_cdd/memory.h" CONTENT)
string(REPLACE "#ifdef CDD_BUILD_TESTS\nextern int g_cdd_alloc_fail;" "extern int g_cdd_alloc_fail;\n#ifdef CDD_BUILD_TESTS" CONTENT "${CONTENT}")
file(WRITE "${SRC}/include/c_cdd/memory.h" "${CONTENT}")

file(READ "${SRC}/src/cdd_api.c" CONTENT)
string(REGEX REPLACE "C_CDD_EXPORT int g_crypto_fail_[a-zA-Z0-9_]+ = 0;\n" "" CONTENT "${CONTENT}")
file(WRITE "${SRC}/src/cdd_api.c" "${CONTENT}")

file(READ "${SRC}/src/classes/emit/json.c" CONTENT)
string(REGEX REPLACE "C_CDD_EXPORT int g_fail_io_after = -1;\n" "extern int g_fail_io_after;\n" CONTENT "${CONTENT}")
string(REGEX REPLACE "C_CDD_EXPORT int g_io_calls = 0;\n" "extern int g_io_calls;\n" CONTENT "${CONTENT}")
file(WRITE "${SRC}/src/classes/emit/json.c" "${CONTENT}")

file(READ "${SRC}/src/routes/parse/cli.c" CONTENT)
string(REGEX REPLACE "strcat\\(final_code," "CDD_STRCPY(final_code + strlen(final_code), sizeof(final_code) - strlen(final_code)," CONTENT "${CONTENT}")
string(REGEX REPLACE "sprintf\\(snippet," "CDD_SNPRINTF(snippet, sizeof(snippet)," CONTENT "${CONTENT}")
file(WRITE "${SRC}/src/routes/parse/cli.c" "${CONTENT}")

file(READ "${SRC}/src/routes/parse/cli.c" CONTENT)
string(REPLACE "#include <stdio.h>" "#include <stdio.h>\n#include \"c_cdd/safe_crt.h\"" CONTENT "${CONTENT}")
file(WRITE "${SRC}/src/routes/parse/cli.c" "${CONTENT}")
file(READ "${SRC}/CMakeLists.txt" CONTENT)
string(REPLACE "/WX" "" CONTENT "${CONTENT}")
string(REPLACE ";-WX;" ";" CONTENT "${CONTENT}")
file(WRITE "${SRC}/CMakeLists.txt" "${CONTENT}")
file(READ "${SRC}/src/functions/parse/analysis.c" CONTENT)
string(REPLACE "if ((rc = allocation_site_list_init(out)) != 0)" "if ((rc = (cdd_c_error_t)allocation_site_list_init(out)) != 0)" CONTENT "${CONTENT}")
string(REPLACE "rc = allocation_site_list_add(" "rc = (cdd_c_error_t)allocation_site_list_add(" CONTENT "${CONTENT}")
file(WRITE "${SRC}/src/functions/parse/analysis.c" "${CONTENT}")
