file(READ "${SRC}/src/http_types.c" CONTENT)
string(REPLACE "static enum c_abstract_http_error c_abstract_http_strdup" "enum c_abstract_http_error c_abstract_http_strdup" CONTENT "${CONTENT}")
file(WRITE "${SRC}/src/http_types.c" "${CONTENT}")

file(GLOB_RECURSE C_FILES "${SRC}/src/*.c")
foreach(F ${C_FILES})
  file(READ "${F}" F_CONTENT)
  string(REPLACE "sprintf(boundary, \\\"------------------------cddbound%08x\\\", rand());" "sprintf(boundary, \"------------------------cddbound%08x\", rand());" F_CONTENT "${F_CONTENT}")
  string(REPLACE "sprintf_s(boundary, sizeof(boundary), \\\"------------------------cddbound%08x\\\", rand());" "sprintf_s(boundary, sizeof(boundary), \"------------------------cddbound%08x\", rand());" F_CONTENT "${F_CONTENT}")
  string(REPLACE "sprintf(ct, \\\"multipart/form-data; boundary=%s\\\", boundary);" "sprintf(ct, \"multipart/form-data; boundary=%s\", boundary);" F_CONTENT "${F_CONTENT}")
  string(REPLACE "sprintf_s(ct, sizeof(ct), \\\"multipart/form-data; boundary=%s\\\", boundary);" "sprintf_s(ct, sizeof(ct), \"multipart/form-data; boundary=%s\", boundary);" F_CONTENT "${F_CONTENT}")
  string(REPLACE "sprintf(val, \\\"Bearer %s\\\", token);" "sprintf(val, \"Bearer %s\", token);" F_CONTENT "${F_CONTENT}")
  string(REPLACE "sprintf_s(val, len, \\\"Bearer %s\\\", token);" "sprintf_s(val, len, \"Bearer %s\", token);" F_CONTENT "${F_CONTENT}")
  string(REPLACE "sprintf(val, \\\"Basic %s\\\", token);" "sprintf(val, \"Basic %s\", token);" F_CONTENT "${F_CONTENT}")
  string(REPLACE "sprintf_s(val, len, \\\"Basic %s\\\", token);" "sprintf_s(val, len, \"Basic %s\", token);" F_CONTENT "${F_CONTENT}")
  string(REPLACE "sprintf(raw, \\\"%s:%s\\\", username, password);" "sprintf(raw, \"%s:%s\", username, password);" F_CONTENT "${F_CONTENT}")
  string(REPLACE "sprintf_s(raw, len, \\\"%s:%s\\\", username, password);" "sprintf_s(raw, len, \"%s:%s\", username, password);" F_CONTENT "${F_CONTENT}")
  string(REPLACE "sprintf(buf, \\\"%s: %s\\\", key, value);" "sprintf(buf, \"%s: %s\", key, value);" F_CONTENT "${F_CONTENT}")
  string(REPLACE "sprintf_s(buf, sizeof(buf), \\\"%s: %s\\\", key, value);" "sprintf_s(buf, sizeof(buf), \"%s: %s\", key, value);" F_CONTENT "${F_CONTENT}")
  file(WRITE "${F}" "${F_CONTENT}")
endforeach()

file(READ "${SRC}/include/c_abstract_http/no_discard.h" NODISC_CONTENT)
string(REPLACE "_Check_return_" "" NODISC_CONTENT "${NODISC_CONTENT}")
file(WRITE "${SRC}/include/c_abstract_http/no_discard.h" "${NODISC_CONTENT}")

file(READ "${SRC}/src/http_wininet.c" WININET_CONTENT)
string(REPLACE "#ifdef _WIN32" "#if defined(_WIN32) || defined(__CYGWIN__)" WININET_CONTENT "${WININET_CONTENT}")
string(REPLACE "#include <wininet.h>" "#include <winsock2.h>\n#include <wininet.h>" WININET_CONTENT "${WININET_CONTENT}")
file(WRITE "${SRC}/src/http_wininet.c" "${WININET_CONTENT}")

file(READ "${SRC}/src/http_winhttp.c" WINHTTP_CONTENT)
string(REPLACE "#ifdef _WIN32" "#if defined(_WIN32) || defined(__CYGWIN__)" WINHTTP_CONTENT "${WINHTTP_CONTENT}")
string(REPLACE "#include <winhttp.h>" "#include <winsock2.h>\n#include <winhttp.h>" WINHTTP_CONTENT "${WINHTTP_CONTENT}")
file(WRITE "${SRC}/src/http_winhttp.c" "${WINHTTP_CONTENT}")
