name: CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    uses: SamuelMarks/c-ci/.github/workflows/c-cmake-ci.yml@master

  msvc-wine:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Checkout c-ci
        uses: actions/checkout@v4
        with:
          repository: SamuelMarks/c-ci
          ref: master
          path: c-ci
      - name: Run MSVC Wine
        run: bash c-ci/build_msvc_wine.sh
