name: CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    timeout-minutes: 15
    uses: SamuelMarks/c-ci/.github/workflows/c-cmake-ci.yml@master
